version: '3'

services:
  lb:
    image: haproxy
    ports: 
        - '8080:8080'
    volumes:
          - ./haproxy:/usr/local/etc/haproxy
  product:
    image: nodeapp
    environment:
      - APPID=1111
  comment:
    image: nodeapp
    environment:
      - APPID=2222
  user:
    image: nodeapp
    environment:
      - APPID=3333
